import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

import { initDatabases, closeDatabases } from './config/dbManager.js';
import { initAllModels } from './models/index.js';
import { Student } from './models/Student.js';
import { Owner } from './models/Owner.js';
import { Hostel } from './models/Hostel.js';
import { College } from './models/College.js';
import { Area } from './models/Area.js';
import { Review } from './models/Review.js';
import { Enquiry } from './models/Enquiry.js';
import { Favourite } from './models/Favourite.js';
import { StudentFeedback } from './models/StudentFeedback.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '.env') });

export const seedDatabase = async () => {
  console.log('--- Starting Vadodara Master Database Seeding ---');

  const { studentDb, hostelDb } = await initDatabases();
  initAllModels({ studentDb, hostelDb });

  // Clear existing collections safely
  await Promise.all([
    Student.deleteMany({}),
    Favourite.deleteMany({}),
    Hostel.deleteMany({}),
    Owner.deleteMany({}),
    College.deleteMany({}),
    Area.deleteMany({}),
    Review.deleteMany({}),
    Enquiry.deleteMany({}),
    StudentFeedback.deleteMany({}),
  ]);

  console.log('Cleared existing collections across both databases.');

  // =========================================================================
  // 1. SEED 6 MASTER COLLEGES (Section 4)
  // =========================================================================
  const collegesData = [
    {
      name: 'Parul University',
      city: 'Vadodara',
      address: 'P.O. Limda, Ta. Waghodia, Vadodara, Gujarat 391760',
      latitude: 22.2965,
      longitude: 73.0169,
      website: 'https://paruluniversity.ac.in',
      type: 'Private University',
    },
    {
      name: 'The Maharaja Sayajirao University of Baroda',
      city: 'Vadodara',
      address: 'Pratapgunj, Fatehgunj, Vadodara, Gujarat 390002',
      latitude: 22.3225,
      longitude: 73.186,
      website: 'https://www.msubaroda.ac.in',
      type: 'State University',
    },
    {
      name: 'ITM SLS Baroda University',
      city: 'Vadodara',
      address: 'Dhanora Tank Road, Paldi, Near Jarod, Vadodara, Gujarat 391510',
      latitude: 22.3561,
      longitude: 73.1928,
      website: 'https://www.itmuniversity.ac.in',
      type: 'Private University',
    },
    {
      name: 'Navrachana University',
      city: 'Vadodara',
      address: 'Vasna-Bhayli Road, Bhayli, Vadodara, Gujarat 391410',
      latitude: 22.368,
      longitude: 73.1415,
      website: 'https://nuv.ac.in',
      type: 'Private University',
    },
    {
      name: 'Sigma University',
      city: 'Vadodara',
      address: 'Bakrol, Waghodia, Vadodara, Gujarat 390019',
      latitude: 22.3582,
      longitude: 73.3421,
      website: 'https://sigmauniversity.ac.in',
      type: 'Private University',
    },
    {
      name: 'GSFC University',
      city: 'Vadodara',
      address: 'Vigyan Bhavan, PO Fertilizernagar, Vadodara, Gujarat 391750',
      latitude: 22.3695,
      longitude: 73.1612,
      website: 'https://www.gsfcuni.edu.in',
      type: 'Private University',
    },
  ];

  const colleges = await College.create(collegesData);
  console.log(`Seeded ${colleges.length} Vadodara Master Colleges.`);

  // Map for easy ID referencing
  const collegeMap = {};
  colleges.forEach((c) => {
    collegeMap[c.name] = c._id;
  });

  // =========================================================================
  // 2. SEED LOCATION MASTER DATA (Section 5)
  // =========================================================================
  const areasList = [
    { name: 'Waghodia', popularFor: ['Parul University', 'Sigma University'] },
    { name: 'Limda', popularFor: ['Parul University Campus', 'Student Hostels'] },
    { name: 'Khatamba', popularFor: ['Gurukuls', 'Dormitories'] },
    { name: 'Bapod', popularFor: ['Waghodia Road Transit', 'Private Hostels'] },
    { name: 'Kendranagar', popularFor: ['Affordable PGs', 'Waghodia Road'] },
    { name: 'Madhavpura', popularFor: ['Student Flats', 'PGs'] },
    { name: 'Fatehgunj', popularFor: ['MSU Main Campus', 'Food Street', 'Cafes'] },
    { name: 'Pratapgunj', popularFor: ['MSU Faculty of Tech', 'MSU Hostels'] },
    { name: 'Sayajigunj', popularFor: ['Baroda Railway Station', 'MSU Commerce'] },
    { name: 'Jayesh Colony', popularFor: ['Fatehgunj Student Hub'] },
    { name: 'Karelibagh', popularFor: ['Amit Nagar Circle', 'Quiet PGs'] },
    { name: 'Amit Nagar', popularFor: ['Express Highway Access', 'Student Stays'] },
    { name: 'Gotri', popularFor: ['Medical College & Hospital', 'Peaceful PGs'] },
    { name: 'Bhayli', popularFor: ['Navrachana University', 'Premium PGs'] },
    { name: 'Vasant Vihar', popularFor: ['Girls Hostels', 'Navrachana Access'] },
    { name: 'Alkapuri', popularFor: ['Commercial Hub', 'Genda Circle', 'Chakli Circle'] },
    { name: 'Akota', popularFor: ['Central Vadodara', 'Parks', 'PGs'] },
    { name: 'Manjalpur', popularFor: ['Gujarat Youth Hostel', 'South Vadodara'] },
    { name: 'New Sama', popularFor: ['Samras Hostel', 'Sama Savli Road'] },
    { name: 'Harni', popularFor: ['Airport Road', 'Hostels'] },
    { name: 'Ajwa Road', popularFor: ['Sigma University Transit', 'Hostels'] },
    { name: 'Vasna', popularFor: ['Vasna Road', 'Navrachana Commute'] },
    { name: 'Atladara', popularFor: ['BAPS Swaminarayan Temple', 'Hostels'] },
    { name: 'Sama Savli', popularFor: ['Modern Townships', 'Student Stays'] },
    { name: 'Old Padra Road', popularFor: ['Corporate Offices', 'PGs'] },
  ];

  await Area.create(areasList);
  console.log(`Seeded ${areasList.length} Vadodara Location Master Areas.`);

  // =========================================================================
  // 3. SEED USERS (ADMIN, OWNERS, STUDENTS)
  // =========================================================================
  const salt = await bcrypt.genSalt(10);
  const studentPassword = await bcrypt.hash('password', salt);
  const adminPassword = await bcrypt.hash('admin123', salt);
  const ownerPassword = await bcrypt.hash('owner123', salt);

  const admin = await Owner.create({
    name: 'Admin User',
    email: 'admin@test.com',
    phone: '9876543200',
    passwordHash: adminPassword,
    businessName: 'StayNear Administration',
    role: 'ADMIN',
    verificationStatus: 'VERIFIED',
  });

  const owner1 = await Owner.create({
    name: 'Rajesh Patel',
    email: 'owner@test.com',
    phone: '9876543210',
    passwordHash: ownerPassword,
    businessName: 'Patel Accommodation Services',
    role: 'OWNER',
    verificationStatus: 'VERIFIED',
  });

  const student1 = await Student.create({
    fullName: 'Rahul Sharma',
    email: 'student@test.com',
    phone: '9876543220',
    passwordHash: studentPassword,
    college: 'Parul University',
    course: 'B.Tech Computer Science',
    year: '2nd Year',
    gender: 'male',
    budgetMin: 4000,
    budgetMax: 7500,
    preferredLocations: ['Limda', 'Waghodia'],
    preferredRoomType: 'Double Sharing',
    preferredAmenities: ['wifi', 'food'],
  });

  console.log('Seeded Admin, Owner, and Student accounts.');

  // =========================================================================
  // 4. SEED 36 INITIAL VADODARA HOSTELS & PGS (Section 6)
  // =========================================================================
  const seedHostelsData = [
    // PARUL / WAGHODIA
    {
      name: 'Hostel A1',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Private student hostel in Waghodia/Limda area near Parul University with high-speed amenities.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919666007700',
      source: 'Verified Vadodara Business Directory',
      sourceUrl: null,
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Parul University Main Gate, Waghodia / Limda, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.298,
        longitude: 73.0185,
        coordinates: [73.0185, 22.298],
      },
      pricing: {
        monthlyRent: 5500,
        annualRent: null,
        securityDeposit: 5000,
        maintenance: 0,
        electricity: 0,
        water: 0,
        food: 1500,
        laundry: 0,
        otherMandatoryCharges: 0,
        effectiveMonthlyCost: 7000,
      },
      rooms: [
        { type: 'DOUBLE', price: 5500, beds: 2, availableBeds: 2, ac: false, attachedBathroom: true, studyTable: true, wardrobe: true },
      ],
      amenities: { wifi: true, food: true, cctv: true, roWater: true, parking: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1500 },
      reviews: { rating: 4.7, reviewCount: 149 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Tagore A Hostel, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      description: 'Official university hostel block on Parul University campus.',
      ownerId: null,
      collegeId: collegeMap['Parul University'],
      phone: null,
      source: 'Official Parul University Accommodation Portal',
      sourceUrl: 'https://paruluniversity.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, Limda, Waghodia, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2965,
        longitude: 73.0169,
        coordinates: [73.0169, 22.2965],
      },
      pricing: {
        monthlyRent: 6000,
        annualRent: 72000,
        securityDeposit: 5000,
        maintenance: 0,
        electricity: 0,
        water: 0,
        food: 0,
        laundry: 0,
        otherMandatoryCharges: 0,
        effectiveMonthlyCost: 6000,
      },
      rooms: [
        { type: 'TRIPLE', price: 6000, beds: 3, availableBeds: 3, ac: false, attachedBathroom: false, studyTable: true, wardrobe: true },
      ],
      amenities: { wifi: true, food: true, cctv: true, securityGuard: true, studyRoom: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: null },
      reviews: { rating: 3.7, reviewCount: 304 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Infinity Hostels',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Private student hostel in Waghodia / Limda near Parul University.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919998006905',
      source: 'Public Hostel Directory',
      sourceUrl: null,
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Limda - Waghodia Road, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2972,
        longitude: 73.019,
        coordinates: [73.019, 22.2972],
      },
      pricing: {
        monthlyRent: 5000,
        annualRent: null,
        securityDeposit: 3000,
        maintenance: 0,
        electricity: null,
        water: null,
        food: null,
        laundry: null,
        otherMandatoryCharges: null,
        effectiveMonthlyCost: 5000,
      },
      amenities: { wifi: true, parking: true, roWater: true },
      reviews: { rating: 3.8, reviewCount: 146 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Code Hostels - Maple House',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS_AND_GIRLS',
      description: 'Modern student living with separate blocks for boys and girls.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919099922434',
      source: 'Public Listing',
      sourceUrl: null,
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Navi Nagri, Pipaliya, Near Parul University, Vadodara',
        area: 'Waghodia',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.3012,
        longitude: 73.023,
        coordinates: [73.023, 22.3012],
      },
      pricing: {
        monthlyRent: 6500,
        effectiveMonthlyCost: 6500,
      },
      amenities: { wifi: true, ac: true, cctv: true, securityGuard: true },
      reviews: { rating: 4.0, reviewCount: 151 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'Urban Hostel',
      type: 'STUDENT_DORMITORY',
      gender: 'BOYS_AND_GIRLS',
      description: 'Student dormitory in Waghodia.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919510515385',
      source: 'Public Listing',
      sourceUrl: null,
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Waghodia, Vadodara',
        area: 'Waghodia',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.3045,
        longitude: 73.018,
        coordinates: [73.018, 22.3045],
      },
      pricing: {
        monthlyRent: 4500,
        effectiveMonthlyCost: 4500,
      },
      amenities: { wifi: true, roWater: true },
      reviews: { rating: 5.0, reviewCount: 6 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: "Shree Marutinandan Boy's Hostel",
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: "Established boys hostel in Bapod / Waghodia road.",
      ownerId: owner1._id,
      phone: '+918238314859',
      source: 'Public Listing',
      sourceUrl: null,
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Bapod, Waghodia Road, Vadodara',
        area: 'Bapod',
        city: 'Vadodara',
        pincode: '390019',
        latitude: 22.306,
        longitude: 73.235,
        coordinates: [73.235, 22.306],
      },
      pricing: { monthlyRent: 4800, effectiveMonthlyCost: 4800 },
      amenities: { wifi: true, food: true, cctv: true },
      reviews: { rating: 4.6, reviewCount: 715 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Vivekanand Hostel',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Large boys hostel near Kendranagar / Waghodia Road.',
      ownerId: owner1._id,
      phone: '+919825594919',
      source: 'Public Listing',
      sourceUrl: null,
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Kendranagar, Waghodia Road, Vadodara',
        area: 'Kendranagar',
        city: 'Vadodara',
        pincode: '390019',
        latitude: 22.303,
        longitude: 73.238,
        coordinates: [73.238, 22.303],
      },
      pricing: { monthlyRent: 4500, effectiveMonthlyCost: 4500 },
      amenities: { wifi: true, cctv: true, roWater: true },
      reviews: { rating: 4.4, reviewCount: 891 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Shree Akshar Gurukul Hostel',
      type: 'STUDENT_DORMITORY',
      gender: 'VERIFY',
      description: 'Student Gurukul dormitory on Waghodia / Khatamba.',
      phone: '+919265184377',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'UNKNOWN',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Pavlepur, Khatamba, Waghodia, Vadodara',
        area: 'Khatamba',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.285,
        longitude: 73.045,
        coordinates: [73.045, 22.285],
      },
      pricing: { monthlyRent: 4000, effectiveMonthlyCost: 4000 },
      reviews: { rating: 4.4, reviewCount: 281 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Kalpataru Hostel PG',
      type: 'STUDENT_DORMITORY',
      gender: 'VERIFY',
      description: 'Hostel and PG on Waghodia Road.',
      phone: '+919879799124',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'UNKNOWN',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Waghodia Road, Vadodara',
        area: 'Waghodia',
        city: 'Vadodara',
        pincode: '390019',
        latitude: 22.302,
        longitude: 73.231,
        coordinates: [73.231, 22.302],
      },
      pricing: { monthlyRent: 4200, effectiveMonthlyCost: 4200 },
      reviews: { rating: 4.4, reviewCount: 19 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'Aadhya PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Clean boys PG in Kendranagar.',
      phone: null,
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Kendranagar, Waghodia Road, Vadodara',
        area: 'Kendranagar',
        city: 'Vadodara',
        pincode: '390019',
        latitude: 22.301,
        longitude: 73.239,
        coordinates: [73.239, 22.301],
      },
      pricing: { monthlyRent: 5000, effectiveMonthlyCost: 5000 },
      reviews: { rating: 5.0, reviewCount: 12 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },

    // FATEHGUNJ / MSU AREA
    {
      name: 'Youth PG Fatehganj',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Well equipped boys PG in Fatehgunj with meals and modern appliances.',
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      totalBeds: 20,
      location: {
        address: 'Near MSU Campus, Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.325,
        longitude: 73.189,
        coordinates: [73.189, 22.325],
      },
      pricing: {
        monthlyRent: 4500,
        effectiveMonthlyCost: 4500,
      },
      rooms: [
        { type: 'TRIPLE', price: 4500, beds: 3, availableBeds: 2, ac: true },
        { type: 'DOUBLE', price: 6000, beds: 2, availableBeds: 1, ac: true },
        { type: 'PRIVATE', price: 8000, beds: 1, availableBeds: 1, ac: true },
      ],
      amenities: {
        ac: true,
        washingMachine: true,
        fridge: true,
        roWater: true,
        cctv: true,
        gatedCommunity: true,
        powerBackup: false,
      },
      food: {
        available: true,
        included: true,
        breakfast: true,
        lunch: true,
        dinner: true,
        vegetarian: true,
      },
      rules: {
        noticePeriod: '30 days',
        lockIn: '3 months',
      },
      reviews: { rating: 4.8, reviewCount: 88 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Girls And Boys PG Vadodara',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Shared co-living PG with AC, fridge, and washing machine.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      totalBeds: 8,
      location: {
        address: 'Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.323,
        longitude: 73.187,
        coordinates: [73.187, 22.323],
      },
      pricing: { monthlyRent: 4500, effectiveMonthlyCost: 4500 },
      rooms: [{ type: 'DOUBLE', price: 4500, beds: 2, availableBeds: 2, ac: true }],
      amenities: { ac: true, washingMachine: true, fridge: true, roWater: true, powerBackup: false },
      rules: { noticePeriod: '30 days', lockIn: '3 months' },
      reviews: { rating: 4.5, reviewCount: 42 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Vishal PG Baroda',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Double sharing PG with AC and washing machine in Fatehgunj.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      totalBeds: 8,
      location: {
        address: 'Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.324,
        longitude: 73.188,
        coordinates: [73.188, 22.324],
      },
      pricing: { monthlyRent: 4500, effectiveMonthlyCost: 4500 },
      rooms: [{ type: 'DOUBLE', price: 4500, beds: 2, availableBeds: 2, ac: true }],
      amenities: { ac: true, washingMachine: true, fridge: true },
      rules: { noticePeriod: '30 days', lockIn: '3 months' },
      reviews: { rating: 4.4, reviewCount: 35 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Somnath PG and Hostel',
      type: 'STUDENT_DORMITORY',
      gender: 'BOYS',
      description: 'Affordable student dormitory in Jayesh Colony / Fatehgunj.',
      phone: '+919537408875',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Jayesh Colony, Fatehgunj, Vadodara',
        area: 'Jayesh Colony',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.327,
        longitude: 73.185,
        coordinates: [73.185, 22.327],
      },
      pricing: { monthlyRent: 4200, effectiveMonthlyCost: 4200 },
      reviews: { rating: 4.9, reviewCount: 46 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'SANSKAR PG AND HOSTEL',
      type: 'STUDENT_DORMITORY',
      gender: 'VERIFY',
      description: 'Hostel and PG in Fatehgunj.',
      phone: '+919265568664',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'UNKNOWN',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.326,
        longitude: 73.186,
        coordinates: [73.186, 22.326],
      },
      pricing: { monthlyRent: 4000, effectiveMonthlyCost: 4000 },
      reviews: { rating: 4.5, reviewCount: 119 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: 'Balaji PG-Hostel Boys',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Boys PG and hostel near MSU campus.',
      phone: '+919979248460',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.322,
        longitude: 73.188,
        coordinates: [73.188, 22.322],
      },
      pricing: { monthlyRent: 4800, effectiveMonthlyCost: 4800 },
      reviews: { rating: 4.9, reviewCount: 21 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Vadodara PG Boys & Girls',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Popular co-ed PG in Fatehgunj.',
      phone: '+917016119861',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Fatehgunj Main Road, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.324,
        longitude: 73.187,
        coordinates: [73.187, 22.324],
      },
      pricing: { monthlyRent: 4600, effectiveMonthlyCost: 4600 },
      reviews: { rating: 4.8, reviewCount: 153 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },

    // ALKAPURI
    {
      name: 'Om Shiv PG and Hostel',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Top-rated boys PG and hostel in Alkapuri.',
      phone: '+919328020552',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.311,
        longitude: 73.172,
        coordinates: [73.172, 22.311],
      },
      pricing: { monthlyRent: 6000, effectiveMonthlyCost: 6000 },
      reviews: { rating: 5.0, reviewCount: 44 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Purohit PG Wala Alkapuri',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Boys hostel accommodation in prime Alkapuri area.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.312,
        longitude: 73.174,
        coordinates: [73.174, 22.312],
      },
      pricing: { monthlyRent: 5500, effectiveMonthlyCost: 5500 },
      reviews: { rating: 4.7, reviewCount: 15 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'Boys PG at Genda Circle',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Boys hostel near Genda Circle, Alkapuri.',
      phone: '+917016583433',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Genda Circle, Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.315,
        longitude: 73.168,
        coordinates: [73.168, 22.315],
      },
      pricing: { monthlyRent: 5800, effectiveMonthlyCost: 5800 },
      reviews: { rating: 4.6, reviewCount: 88 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: 'Alak Accommodation',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Established private hostel in Alkapuri.',
      phone: '+918320000902',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.31,
        longitude: 73.175,
        coordinates: [73.175, 22.31],
      },
      pricing: { monthlyRent: 5200, effectiveMonthlyCost: 5200 },
      reviews: { rating: 4.5, reviewCount: 168 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Boys PG at Chakli Circle',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Boys PG located near Chakli Circle, Alkapuri.',
      phone: '+919825050553',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Chakli Circle, Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.308,
        longitude: 73.171,
        coordinates: [73.171, 22.308],
      },
      pricing: { monthlyRent: 5000, effectiveMonthlyCost: 5000 },
      reviews: { rating: 4.4, reviewCount: 24 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },

    // BHAYLI / NAVRACHANA
    {
      name: 'RoomPe Girls Hostel',
      type: 'PRIVATE_HOSTEL',
      gender: 'GIRLS',
      description: 'Safe and secure girls hostel in Bhayli / Vasant Vihar near Navrachana University.',
      collegeId: collegeMap['Navrachana University'],
      phone: '+918469516137',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Vasant Vihar, Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.366,
        longitude: 73.142,
        coordinates: [73.142, 22.366],
      },
      pricing: { monthlyRent: 7500, effectiveMonthlyCost: 7500 },
      amenities: { wifi: true, ac: true, cctv: true, femaleWarden: true, roWater: true },
      reviews: { rating: 4.7, reviewCount: 26 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Premium PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Luxury boys PG in Bhayli with gym, lift, and gated community.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      totalBeds: 6,
      location: {
        address: 'Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.369,
        longitude: 73.14,
        coordinates: [73.14, 22.369],
      },
      pricing: { monthlyRent: 7000, effectiveMonthlyCost: 7000 },
      rooms: [
        { type: 'DOUBLE', price: 7000, beds: 2, availableBeds: 2, ac: true },
        { type: 'PRIVATE', price: 11000, beds: 1, availableBeds: 1, ac: true },
      ],
      amenities: {
        diningTable: true,
        washingMachine: true,
        ac: true,
        fridge: true,
        gatedCommunity: true,
        gym: true,
        cctv: true,
        lift: true,
        powerBackup: false,
      },
      rules: { noticePeriod: '30 days', lockIn: '1 day' },
      reviews: { rating: 4.8, reviewCount: 18 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'PARUL PG',
      type: 'PRIVATE_PG',
      gender: 'GIRLS',
      description: 'Exclusive girls PG in Bhayli with optional complete meal plan and parking.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      totalBeds: 7,
      location: {
        address: 'Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.3675,
        longitude: 73.143,
        coordinates: [73.143, 22.3675],
      },
      pricing: {
        monthlyRent: 8000,
        food: 5000,
        electricity: 1000,
        effectiveMonthlyCost: 14000,
      },
      rooms: [
        { type: 'TRIPLE', price: 8000, beds: 3, availableBeds: 2 },
        { type: 'DOUBLE', price: 10000, beds: 2, availableBeds: 1 },
        { type: 'PRIVATE', price: 12000, beds: 1, availableBeds: 1 },
      ],
      food: { available: true, included: false, breakfast: true, lunch: true, dinner: true, monthlyCost: 5000 },
      amenities: { parking: true, cctv: true, femaleWarden: true },
      rules: { noticePeriod: '30 days', lockIn: '3 months' },
      reviews: { rating: 4.6, reviewCount: 15 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },

    // GOTRI
    {
      name: 'GOTRI PG Boys and Girls',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Co-living PG in peaceful Gotri area.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Gotri Road, Vadodara',
        area: 'Gotri',
        city: 'Vadodara',
        pincode: '390021',
        latitude: 22.316,
        longitude: 73.145,
        coordinates: [73.145, 22.316],
      },
      pricing: { monthlyRent: 5200, effectiveMonthlyCost: 5200 },
      reviews: { rating: 4.9, reviewCount: 66 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Gotri Home Stay PG Boys & Girls',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Home stay style accommodation in Gotri.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Gotri, Vadodara',
        area: 'Gotri',
        city: 'Vadodara',
        pincode: '390021',
        latitude: 22.318,
        longitude: 73.148,
        coordinates: [73.148, 22.318],
      },
      pricing: { monthlyRent: 5500, effectiveMonthlyCost: 5500 },
      reviews: { rating: 5.0, reviewCount: 4 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Swami PG Vadodara',
      type: 'STUDENT_DORMITORY',
      gender: 'BOYS',
      description: 'Dormitory style accommodation in Gotri.',
      phone: '+919714925598',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Gotri, Vadodara',
        area: 'Gotri',
        city: 'Vadodara',
        pincode: '390021',
        latitude: 22.314,
        longitude: 73.143,
        coordinates: [73.143, 22.314],
      },
      pricing: { monthlyRent: 4300, effectiveMonthlyCost: 4300 },
      reviews: { rating: 4.6, reviewCount: 122 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },

    // KARELIBAGH / AMIT NAGAR
    {
      name: 'Karelibaug PG And Hostel',
      type: 'STUDENT_DORMITORY',
      gender: 'VERIFY',
      description: 'Dormitory style PG in Karelibagh.',
      phone: '+919726268695',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Karelibagh, Vadodara',
        area: 'Karelibagh',
        city: 'Vadodara',
        pincode: '390018',
        latitude: 22.332,
        longitude: 73.205,
        coordinates: [73.205, 22.332],
      },
      pricing: { monthlyRent: 4200, effectiveMonthlyCost: 4200 },
      reviews: { rating: 4.2, reviewCount: 20 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'Bhavesh PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Private PG rooms in Karelibagh.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Karelibagh, Vadodara',
        area: 'Karelibagh',
        city: 'Vadodara',
        pincode: '390018',
        latitude: 22.334,
        longitude: 73.208,
        coordinates: [73.208, 22.334],
      },
      pricing: { monthlyRent: 5000, effectiveMonthlyCost: 5000 },
      rooms: [
        { type: 'DOUBLE', price: 5000, beds: 2, availableBeds: 2 },
        { type: 'PRIVATE', price: 6000, beds: 1, availableBeds: 1 },
      ],
      reviews: { rating: 4.3, reviewCount: 11 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: 'Jatin Bhai Boys and Girls PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS_AND_GIRLS',
      description: 'Budget-friendly PG in Karelibagh.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Karelibagh, Vadodara',
        area: 'Karelibagh',
        city: 'Vadodara',
        pincode: '390018',
        latitude: 22.331,
        longitude: 73.206,
        coordinates: [73.206, 22.331],
      },
      pricing: { monthlyRent: 4000, effectiveMonthlyCost: 4000 },
      rooms: [{ type: 'DOUBLE', price: 4000, beds: 2, availableBeds: 2 }],
      reviews: { rating: 4.4, reviewCount: 16 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },

    // MANJALPUR
    {
      name: 'Shyam Elite Stay PG',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Premium boys PG in Manjalpur with food provided.',
      phone: '+918511096637',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Manjalpur, Vadodara',
        area: 'Manjalpur',
        city: 'Vadodara',
        pincode: '390011',
        latitude: 22.272,
        longitude: 73.195,
        coordinates: [73.195, 22.272],
      },
      pricing: { monthlyRent: 5500, effectiveMonthlyCost: 5500 },
      food: { available: true, included: true, vegetarian: true },
      amenities: { wifi: true, food: true, cctv: true },
      reviews: { rating: 5.0, reviewCount: 14 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Manjalpur Boys PG / Gujarat Youth Hostel',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Hostel stay in Manjalpur.',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Manjalpur, Vadodara',
        area: 'Manjalpur',
        city: 'Vadodara',
        pincode: '390011',
        latitude: 22.275,
        longitude: 73.198,
        coordinates: [73.198, 22.275],
      },
      pricing: { monthlyRent: 4200, effectiveMonthlyCost: 4200 },
      reviews: { rating: 4.6, reviewCount: 10 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Jai Sri Krishna PG',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Economical boys hostel in Manjalpur.',
      phone: '+916356464527',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Manjalpur, Vadodara',
        area: 'Manjalpur',
        city: 'Vadodara',
        pincode: '390011',
        latitude: 22.271,
        longitude: 73.192,
        coordinates: [73.192, 22.271],
      },
      pricing: { monthlyRent: 3800, effectiveMonthlyCost: 3800 },
      reviews: { rating: 3.7, reviewCount: 41 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },

    // SAMA / SAYAJIGUNJ
    {
      name: "Samras Boy's Hostel",
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: "Large student hostel in New Sama / Kasturba Nagar.",
      phone: '+912652714346',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Kasturba Nagar, New Sama, Vadodara',
        area: 'New Sama',
        city: 'Vadodara',
        pincode: '390024',
        latitude: 22.345,
        longitude: 73.199,
        coordinates: [73.199, 22.345],
      },
      pricing: { monthlyRent: 3500, effectiveMonthlyCost: 3500 },
      amenities: { wifi: true, securityGuard: true, sports: true },
      reviews: { rating: 4.3, reviewCount: 808 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: 'Boys PG Sayajigunj',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Conveniently located boys PG near Baroda Railway Station in Sayajigunj.',
      phone: '+917359516853',
      source: 'Public Listing',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Railway Station, Sayajigunj, Vadodara',
        area: 'Sayajigunj',
        city: 'Vadodara',
        pincode: '390005',
        latitude: 22.313,
        longitude: 73.184,
        coordinates: [73.184, 22.313],
      },
      pricing: { monthlyRent: 4800, effectiveMonthlyCost: 4800 },
      amenities: { wifi: true, roWater: true, cctv: true },
      reviews: { rating: 4.6, reviewCount: 27 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
  ];

  // =========================================================================
  // 5. SEED OFFICIAL UNIVERSITY HOSTELS (Section 7)
  // =========================================================================
  const universityHostels = [
    // PARUL UNIVERSITY OFFICIAL HOSTELS
    {
      name: 'Shastri Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal (2026-27)',
      sourceUrl: 'https://paruluniversity.ac.in/accommodation',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, P.O. Limda, Waghodia, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2965,
        longitude: 73.0169,
        coordinates: [73.0169, 22.2965],
      },
      pricing: { monthlyRent: 6500, annualRent: 78000, effectiveMonthlyCost: 6500 },
      amenities: { wifi: true, food: true, housekeeping: true, powerBackup: true, cctv: true, securityGuard: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true },
      reviews: { rating: 4.1, reviewCount: 140 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    },
    {
      name: 'Ratan Tata Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal (2026-27)',
      sourceUrl: 'https://paruluniversity.ac.in/accommodation',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, P.O. Limda, Waghodia, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2968,
        longitude: 73.0172,
        coordinates: [73.0172, 22.2968],
      },
      pricing: { monthlyRent: 7000, annualRent: 84000, effectiveMonthlyCost: 7000 },
      amenities: { wifi: true, ac: true, food: true, cctv: true, securityGuard: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true },
      reviews: { rating: 4.3, reviewCount: 95 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'Sarojini Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal (2026-27)',
      sourceUrl: 'https://paruluniversity.ac.in/accommodation',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, P.O. Limda, Waghodia, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2962,
        longitude: 73.0165,
        coordinates: [73.0165, 22.2962],
      },
      pricing: { monthlyRent: 6500, annualRent: 78000, effectiveMonthlyCost: 6500 },
      amenities: { wifi: true, food: true, cctv: true, femaleWarden: true, securityGuard: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true },
      reviews: { rating: 4.2, reviewCount: 110 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    },
    {
      name: 'Abraham Lincoln Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, Limda, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.297,
        longitude: 73.0175,
        coordinates: [73.0175, 22.297],
      },
      pricing: { monthlyRent: 6000, annualRent: 72000, effectiveMonthlyCost: 6000 },
      amenities: { wifi: true, food: true, cctv: true },
      food: { available: true, included: true, vegetarian: true },
      reviews: { rating: 4.0, reviewCount: 85 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'Teresa Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, Limda, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.296,
        longitude: 73.0162,
        coordinates: [73.0162, 22.296],
      },
      pricing: { monthlyRent: 6500, annualRent: 78000, effectiveMonthlyCost: 6500 },
      amenities: { wifi: true, food: true, femaleWarden: true, cctv: true },
      food: { available: true, included: true, vegetarian: true },
      reviews: { rating: 4.1, reviewCount: 78 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },
    {
      name: 'Indira Bhawan, Parul University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['Parul University'],
      source: 'Official Parul University Accommodation Portal',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Parul University Campus, Limda, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2961,
        longitude: 73.0164,
        coordinates: [73.0164, 22.2961],
      },
      pricing: { monthlyRent: 6500, annualRent: 78000, effectiveMonthlyCost: 6500 },
      amenities: { wifi: true, food: true, femaleWarden: true, cctv: true },
      food: { available: true, included: true, vegetarian: true },
      reviews: { rating: 4.0, reviewCount: 62 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },

    // THE MAHARAJA SAYAJIRAO UNIVERSITY (MSU) OFFICIAL HALLS OF RESIDENCE
    ...[
      'Jivraj Mehta Hall',
      'K. M. Munshi Hall',
      'Lal Bahadur Shastri Hall',
      'Maharshi Arvind Hall',
      'Manubhai Mehta Hall',
      'Nusservanji Vakil Hall',
      'Sardar Patel Hall',
      'T. K. Gajjar Hall',
      'Vikram Sarabhai Hall',
      'Sir M. Visvesvaraya Hall',
      'Rabindranath Tagore Hall',
      'Siddharaj Jaisinh Hall',
    ].map((name, idx) => ({
      name: `${name}, MS University`,
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      source: 'Official MSU Halls of Residence',
      sourceUrl: 'https://www.msubaroda.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'MSU Halls of Residence, Pratapgunj, Vadodara',
        area: 'Pratapgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.3225 + idx * 0.001,
        longitude: 73.186 + idx * 0.0008,
        coordinates: [73.186 + idx * 0.0008, 22.3225 + idx * 0.001],
      },
      pricing: { monthlyRent: 1500, annualRent: 18000, effectiveMonthlyCost: 1500 },
      amenities: { wifi: true, studyRoom: true, sports: true, commonRoom: true, securityGuard: true },
      food: { available: true, included: false, vegetarian: true },
      reviews: { rating: 4.0, reviewCount: 150 + idx * 10 },
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
    })),

    // MSU GIRLS HALLS OF RESIDENCE
    ...[
      'Hansa Mehta Hall',
      'Kasturba Gandhi Hall',
      'Pandita Gargi Hall',
      'Sarojini Devi Hall',
    ].map((name, idx) => ({
      name: `${name}, MS University`,
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      source: 'Official MSU Halls of Residence (Women)',
      sourceUrl: 'https://www.msubaroda.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'MSU Women Halls of Residence, Fatehgunj / Pratapgunj, Vadodara',
        area: 'Pratapgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.324 + idx * 0.001,
        longitude: 73.187 + idx * 0.0008,
        coordinates: [73.187 + idx * 0.0008, 22.324 + idx * 0.001],
      },
      pricing: { monthlyRent: 1500, annualRent: 18000, effectiveMonthlyCost: 1500 },
      amenities: { wifi: true, femaleWarden: true, securityGuard: true, studyRoom: true, cctv: true },
      food: { available: true, included: false, vegetarian: true },
      reviews: { rating: 4.2, reviewCount: 120 + idx * 15 },
      images: ['https://images.unsplash.com/photo-1540518614846-7ede433c4b69?w=800&q=80'],
    })),

    // NAVRACHANA UNIVERSITY OFFICIAL HOSTELS
    {
      name: 'Kshitij Apartments, Navrachana University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['Navrachana University'],
      source: 'Official Navrachana University Accommodation Guidelines',
      sourceUrl: 'https://nuv.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Vasna-Bhayli Road, Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.3682,
        longitude: 73.1418,
        coordinates: [73.1418, 22.3682],
      },
      pricing: { monthlyRent: 8500, annualRent: 102000, effectiveMonthlyCost: 8500 },
      rooms: [
        { type: 'SINGLE', price: 12000, beds: 1, availableBeds: 1, ac: true },
        { type: 'DOUBLE', price: 9500, beds: 2, availableBeds: 2, ac: true },
        { type: 'TRIPLE', price: 8500, beds: 3, availableBeds: 3, ac: true },
      ],
      amenities: { wifi: true, ac: true, cctv: true, femaleWarden: true, securityGuard: true, lift: true, gym: true },
      reviews: { rating: 4.6, reviewCount: 48 },
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    },
    {
      name: 'The Emerald, Navrachana University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['Navrachana University'],
      source: 'Official Navrachana University Accommodation Guidelines',
      sourceUrl: 'https://nuv.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Vasna-Bhayli Road, Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.3685,
        longitude: 73.1422,
        coordinates: [73.1422, 22.3685],
      },
      pricing: { monthlyRent: 8000, annualRent: 96000, effectiveMonthlyCost: 8000 },
      rooms: [
        { type: 'SINGLE', price: 12000, beds: 1, availableBeds: 1, ac: true },
        { type: 'DOUBLE', price: 9500, beds: 2, availableBeds: 2, ac: true },
        { type: 'TRIPLE', price: 8000, beds: 3, availableBeds: 3, ac: true },
        { type: 'FOUR', price: 7000, beds: 4, availableBeds: 4, ac: false },
      ],
      amenities: { wifi: true, ac: true, cctv: true, securityGuard: true, studyRoom: true, gym: true },
      reviews: { rating: 4.5, reviewCount: 52 },
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    },

    // ITM SLS BARODA UNIVERSITY OFFICIAL HOSTELS
    {
      name: 'ITM Boys Hostel Block, ITM SLS Baroda University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'BOYS',
      collegeId: collegeMap['ITM SLS Baroda University'],
      source: 'Official ITM SLS Baroda University Accommodation Portal',
      sourceUrl: 'https://www.itmuniversity.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Dhanora Tank Road, Paldi, Near Jarod, Vadodara',
        area: 'Waghodia',
        city: 'Vadodara',
        pincode: '391510',
        latitude: 22.3561,
        longitude: 73.1928,
        coordinates: [73.1928, 22.3561],
      },
      pricing: { monthlyRent: 6000, annualRent: 72000, effectiveMonthlyCost: 6000 },
      rooms: [
        { type: 'SINGLE', price: 8500, beds: 1, availableBeds: 1, ac: true },
        { type: 'DOUBLE', price: 6000, beds: 2, availableBeds: 2, ac: false },
      ],
      amenities: { wifi: true, food: true, cctv: true, securityGuard: true, studyRoom: true, commonRoom: true, sports: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true },
      reviews: { rating: 4.2, reviewCount: 65 },
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80'],
    },
    {
      name: 'ITM Girls Hostel Block, ITM SLS Baroda University',
      type: 'UNIVERSITY_HOSTEL',
      gender: 'GIRLS',
      collegeId: collegeMap['ITM SLS Baroda University'],
      source: 'Official ITM SLS Baroda University Accommodation Portal',
      sourceUrl: 'https://www.itmuniversity.ac.in',
      sourceType: 'OFFICIAL_UNIVERSITY',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Dhanora Tank Road, Paldi, Near Jarod, Vadodara',
        area: 'Waghodia',
        city: 'Vadodara',
        pincode: '391510',
        latitude: 22.3564,
        longitude: 73.1932,
        coordinates: [73.1932, 22.3564],
      },
      pricing: { monthlyRent: 6000, annualRent: 72000, effectiveMonthlyCost: 6000 },
      rooms: [
        { type: 'SINGLE', price: 8500, beds: 1, availableBeds: 1, ac: true },
        { type: 'DOUBLE', price: 6000, beds: 2, availableBeds: 2, ac: false },
      ],
      amenities: { wifi: true, food: true, femaleWarden: true, cctv: true, securityGuard: true, studyRoom: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true },
    },

    // =========================================================================
    // 15 LUXURY / PREMIUM STUDENT SUITES & CO-LIVING (₹16,000 - ₹22,000 / mo)
    // =========================================================================
    {
      name: 'The Grand Alkapuri Luxury Student Suites',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'Ultra-premium student studio residences in Alkapuri with daily housekeeping, private AC suites, gym, and gourmet dining.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500101',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'OWNER_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'RC Dutt Road, Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.3120,
        longitude: 73.1710,
        coordinates: [73.1710, 22.3120],
      },
      pricing: { monthlyRent: 16500, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 19500 },
      rooms: [
        { type: 'SINGLE', price: 19500, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true, studyTable: true, wardrobe: true },
        { type: 'DOUBLE', price: 15000, beds: 2, availableBeds: 3, ac: true, attachedBathroom: true, studyTable: true, wardrobe: true },
      ],
      amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true, gym: true, cctv: true, securityGuard: true, lift: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.8, reviewCount: 42 },
    },
    {
      name: 'Stanza Living - Vadodara Prime House',
      type: 'CO_LIVING',
      gender: 'BOYS',
      description: 'Professionally managed modern student co-living with smart access, high-speed gaming Wi-Fi, and laundry service.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500102',
      source: 'Verified Partner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Akota Garden, Akota, Vadodara',
        area: 'Akota',
        city: 'Vadodara',
        pincode: '390020',
        latitude: 22.2985,
        longitude: 73.1650,
        coordinates: [73.1650, 22.2985],
      },
      pricing: { monthlyRent: 15500, securityDeposit: 12000, food: 2500, effectiveMonthlyCost: 18000 },
      rooms: [
        { type: 'SINGLE', price: 18000, beds: 1, availableBeds: 1, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 13500, beds: 2, availableBeds: 4, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true, gym: true, cctv: true, securityGuard: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 2500 },
      reviews: { rating: 4.7, reviewCount: 78 },
    },
    {
      name: 'Prestige Co-Living Residence',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'Exclusive student suites on Vasna-Bhayli road near Navrachana University with private balconies, pool access, and cafe.',
      ownerId: owner1._id,
      collegeId: collegeMap['Navrachana University'],
      phone: '+919876500103',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'OWNER_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Vasna-Bhayli Main Road, Bhayli, Vadodara',
        area: 'Bhayli',
        city: 'Vadodara',
        pincode: '391410',
        latitude: 22.3650,
        longitude: 73.1380,
        coordinates: [73.1380, 22.3650],
      },
      pricing: { monthlyRent: 18000, securityDeposit: 20000, food: 3000, effectiveMonthlyCost: 21000 },
      rooms: [
        { type: 'SINGLE', price: 21000, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true, balcony: true },
        { type: 'DOUBLE', price: 16000, beds: 2, availableBeds: 2, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, gym: true, lift: true, powerBackup: true, cctv: true, securityGuard: true, studyRoom: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.9, reviewCount: 35 },
    },
    {
      name: 'Elite Scholar Residence for Girls',
      type: 'PRIVATE_PG',
      gender: 'GIRLS',
      description: 'High-security boutique girls residence in Alkapuri with biometric locks, dedicated study rooms, and in-house nutritious kitchen.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500104',
      source: 'Verified Owner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Alkapuri Society, Near Railway Station, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.3150,
        longitude: 73.1740,
        coordinates: [73.1740, 22.3150],
      },
      pricing: { monthlyRent: 15500, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 18500 },
      rooms: [
        { type: 'SINGLE', price: 18500, beds: 1, availableBeds: 1, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 14000, beds: 2, availableBeds: 2, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, femaleWarden: true, cctv: true, securityGuard: true, housekeeping: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.8, reviewCount: 56 },
    },
    {
      name: 'Silver Oak Luxury Boys Studio',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Contemporary bachelor studio PG on Sun Pharma Road with 24/7 power backup, parking, and daily laundry.',
      ownerId: owner1._id,
      collegeId: collegeMap['Navrachana University'],
      phone: '+919876500105',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Sun Pharma Road, Atladara, Vadodara',
        area: 'Atladara',
        city: 'Vadodara',
        pincode: '390012',
        latitude: 22.2850,
        longitude: 73.1520,
        coordinates: [73.1520, 22.2850],
      },
      pricing: { monthlyRent: 16000, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 19000 },
      rooms: [
        { type: 'SINGLE', price: 19000, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, parking: true, housekeeping: true, cctv: true, securityGuard: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.6, reviewCount: 31 },
    },
    {
      name: 'Opulence Student Suites',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Luxury AC student accommodation in Sayajigunj within walking distance of MS University campus and city transport.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500106',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Opposite Sayajigunj Police Station, Sayajigunj, Vadodara',
        area: 'Sayajigunj',
        city: 'Vadodara',
        pincode: '390005',
        latitude: 22.3100,
        longitude: 73.1850,
        coordinates: [73.1850, 22.3100],
      },
      pricing: { monthlyRent: 15000, securityDeposit: 12000, food: 2500, effectiveMonthlyCost: 17500 },
      rooms: [
        { type: 'SINGLE', price: 17500, beds: 1, availableBeds: 3, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 13000, beds: 2, availableBeds: 4, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, lift: true, cctv: true, securityGuard: true, housekeeping: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 2500 },
      reviews: { rating: 4.5, reviewCount: 64 },
    },
    {
      name: 'Crown Executive Co-Living',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'Premium serviced student apartments with kitchenette, gym, recreation lounge, and high-speed Wi-Fi in Gotri.',
      ownerId: owner1._id,
      collegeId: collegeMap['Navrachana University'],
      phone: '+919876500107',
      source: 'Verified Partner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'OWNER_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Gotri-Sevasi Road, Gotri, Vadodara',
        area: 'Gotri',
        city: 'Vadodara',
        pincode: '390021',
        latitude: 22.3250,
        longitude: 73.1410,
        coordinates: [73.1410, 22.3250],
      },
      pricing: { monthlyRent: 17000, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 20000 },
      rooms: [
        { type: 'SINGLE', price: 20000, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 15000, beds: 2, availableBeds: 4, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, gym: true, laundry: true, housekeeping: true, cctv: true, lift: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.7, reviewCount: 49 },
    },
    {
      name: 'Royal Residency Student Living',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'Top-tier luxury student residence near Race Course Circle with fully furnished AC rooms, ergonomic desks, and concierge.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500108',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Race Course Circle, Alkapuri, Vadodara',
        area: 'Alkapuri',
        city: 'Vadodara',
        pincode: '390007',
        latitude: 22.3160,
        longitude: 73.1680,
        coordinates: [73.1680, 22.3160],
      },
      pricing: { monthlyRent: 19000, securityDeposit: 20000, food: 3000, effectiveMonthlyCost: 22000 },
      rooms: [
        { type: 'SINGLE', price: 22000, beds: 1, availableBeds: 1, ac: true, attachedBathroom: true, balcony: true },
      ],
      amenities: { wifi: true, food: true, ac: true, gym: true, housekeeping: true, laundry: true, cctv: true, lift: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.9, reviewCount: 38 },
    },
    {
      name: 'Aura Luxury Girls Living',
      type: 'PRIVATE_PG',
      gender: 'GIRLS',
      description: 'Exclusive AC student residence for female scholars in Fatehgunj with 24/7 security warden, gourmet meals, and lift.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500109',
      source: 'Verified Owner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Pratapgunj Main Road, Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.3240,
        longitude: 73.1870,
        coordinates: [73.1870, 22.3240],
      },
      pricing: { monthlyRent: 15000, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 18000 },
      rooms: [
        { type: 'SINGLE', price: 18000, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 13500, beds: 2, availableBeds: 3, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, femaleWarden: true, lift: true, cctv: true, housekeeping: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.8, reviewCount: 51 },
    },
    {
      name: 'Skyline Student Apartments',
      type: 'CO_LIVING',
      gender: 'BOYS',
      description: 'Spacious student apartments in Karelibaug with high-speed fiber internet, study lounge, and homestyle food.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500110',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Karelibaug Water Tank Road, Vadodara',
        area: 'Karelibaug',
        city: 'Vadodara',
        pincode: '390018',
        latitude: 22.3290,
        longitude: 73.1980,
        coordinates: [73.1980, 22.3290],
      },
      pricing: { monthlyRent: 14500, securityDeposit: 12000, food: 2500, effectiveMonthlyCost: 17000 },
      rooms: [
        { type: 'SINGLE', price: 17000, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 12500, beds: 2, availableBeds: 4, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, parking: true, housekeeping: true, cctv: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 2500 },
      reviews: { rating: 4.5, reviewCount: 44 },
    },
    {
      name: 'The Palm Luxury Co-Living',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'High-end co-living space on Sama-Savli road featuring cafeteria, fitness center, and furnished studio rooms.',
      ownerId: owner1._id,
      collegeId: collegeMap['GSFC University'],
      phone: '+919876500111',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'OWNER_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Sama-Savli Road, Sama, Vadodara',
        area: 'Sama',
        city: 'Vadodara',
        pincode: '390024',
        latitude: 22.3480,
        longitude: 73.1890,
        coordinates: [73.1890, 22.3480],
      },
      pricing: { monthlyRent: 16500, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 19500 },
      rooms: [
        { type: 'SINGLE', price: 19500, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 14500, beds: 2, availableBeds: 3, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, gym: true, lift: true, laundry: true, housekeeping: true, cctv: true, securityGuard: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.7, reviewCount: 39 },
    },
    {
      name: 'Signature Suites for Scholars',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Executive student suites in Manjalpur offering single AC rooms, daily housekeeping, and premium vegetarian mess.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500112',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Manjalpur Main Road, Manjalpur, Vadodara',
        area: 'Manjalpur',
        city: 'Vadodara',
        pincode: '390011',
        latitude: 22.2710,
        longitude: 73.1950,
        coordinates: [73.1950, 22.2710],
      },
      pricing: { monthlyRent: 15500, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 18500 },
      rooms: [
        { type: 'SINGLE', price: 18500, beds: 1, availableBeds: 1, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, housekeeping: true, parking: true, cctv: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.6, reviewCount: 28 },
    },
    {
      name: 'Heritage Executive Student PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Colonial style premium single AC student rooms in Pratapgunj with garden view, home-cooked food, and Wi-Fi.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500113',
      source: 'Verified Owner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'OWNER_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Pratapgunj Society, Vadodara',
        area: 'Pratapgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.3210,
        longitude: 73.1890,
        coordinates: [73.1890, 22.3210],
      },
      pricing: { monthlyRent: 14500, securityDeposit: 12000, food: 3000, effectiveMonthlyCost: 17500 },
      rooms: [
        { type: 'SINGLE', price: 17500, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, parking: true, housekeeping: true, cctv: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.8, reviewCount: 33 },
    },
    {
      name: 'Imperia Luxury Girls PG',
      type: 'PRIVATE_PG',
      gender: 'GIRLS',
      description: 'Deluxe AC accommodation for female students in Akota with high security, balanced diet, and laundry.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500114',
      source: 'Verified Owner Listing',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Akota Stadium Road, Akota, Vadodara',
        area: 'Akota',
        city: 'Vadodara',
        pincode: '390020',
        latitude: 22.2960,
        longitude: 73.1670,
        coordinates: [73.1670, 22.2960],
      },
      pricing: { monthlyRent: 16000, securityDeposit: 15000, food: 3000, effectiveMonthlyCost: 19000 },
      rooms: [
        { type: 'SINGLE', price: 19000, beds: 1, availableBeds: 1, ac: true, attachedBathroom: true },
        { type: 'DOUBLE', price: 14500, beds: 2, availableBeds: 3, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, femaleWarden: true, cctv: true, housekeeping: true, laundry: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.8, reviewCount: 46 },
    },
    {
      name: 'Urban Nest Premium Student Co-Living',
      type: 'CO_LIVING',
      gender: 'BOYS_AND_GIRLS',
      description: 'Smart student co-living with digital keyless entry, fitness gym, gaming lounge, and chef-curated meals in Vasna.',
      ownerId: owner1._id,
      collegeId: collegeMap['Navrachana University'],
      phone: '+919876500115',
      source: 'Verified Property Management',
      sourceType: 'VERIFIED_BUSINESS',
      verificationStatus: 'ADMIN_VERIFIED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Vasna Road, Near D-Mart, Vadodara',
        area: 'Vasna Road',
        city: 'Vadodara',
        pincode: '390015',
        latitude: 22.3020,
        longitude: 73.1490,
        coordinates: [73.1490, 22.3020],
      },
      pricing: { monthlyRent: 18500, securityDeposit: 20000, food: 3000, effectiveMonthlyCost: 21500 },
      rooms: [
        { type: 'SINGLE', price: 21500, beds: 1, availableBeds: 2, ac: true, attachedBathroom: true, balcony: true },
        { type: 'DOUBLE', price: 16500, beds: 2, availableBeds: 2, ac: true, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, ac: true, gym: true, lift: true, laundry: true, housekeeping: true, cctv: true, powerBackup: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 3000 },
      reviews: { rating: 4.9, reviewCount: 53 },
    },

    // =========================================================================
    // 5 BUDGET / AFFORDABLE STUDENT HOSTELS & PGS (₹5,000 - ₹7,500 / mo)
    // =========================================================================
    {
      name: 'Saraswati Student PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Affordable student PG in Limda village within 1 km of Parul University campus with meals and Wi-Fi.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919876500116',
      source: 'Verified Local Directory',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Limda Village, Near Parul Gate 2, Waghodia, Vadodara',
        area: 'Limda',
        city: 'Vadodara',
        pincode: '391760',
        latitude: 22.2950,
        longitude: 73.0210,
        coordinates: [73.0210, 22.2950],
      },
      pricing: { monthlyRent: 4500, securityDeposit: 4000, food: 1500, effectiveMonthlyCost: 6000 },
      rooms: [
        { type: 'DOUBLE', price: 6000, beds: 2, availableBeds: 4, ac: false, attachedBathroom: true },
        { type: 'TRIPLE', price: 5000, beds: 3, availableBeds: 6, ac: false, attachedBathroom: false },
      ],
      amenities: { wifi: true, food: true, roWater: true, parking: true, cctv: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1500 },
      reviews: { rating: 4.3, reviewCount: 39 },
    },
    {
      name: 'Ganesh Krupa Boys Hostel',
      type: 'PRIVATE_HOSTEL',
      gender: 'BOYS',
      description: 'Economical student hostel near MS University Polytech campus in Fatehgunj with mess and hot water.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500117',
      source: 'Verified Local Directory',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Polytech Ground, Fatehgunj, Vadodara',
        area: 'Fatehgunj',
        city: 'Vadodara',
        pincode: '390002',
        latitude: 22.3270,
        longitude: 73.1890,
        coordinates: [73.1890, 22.3270],
      },
      pricing: { monthlyRent: 5000, securityDeposit: 5000, food: 1500, effectiveMonthlyCost: 6500 },
      rooms: [
        { type: 'TRIPLE', price: 6500, beds: 3, availableBeds: 3, ac: false, attachedBathroom: true },
        { type: 'FOUR', price: 5500, beds: 4, availableBeds: 8, ac: false, attachedBathroom: false },
      ],
      amenities: { wifi: true, food: true, cctv: true, roWater: true, studyTable: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1500 },
      reviews: { rating: 4.1, reviewCount: 45 },
    },
    {
      name: 'Radhe Girls PG',
      type: 'PRIVATE_PG',
      gender: 'GIRLS',
      description: 'Budget-friendly and safe PG for female students on Waghodia road with home-style food and female warden.',
      ownerId: owner1._id,
      collegeId: collegeMap['Parul University'],
      phone: '+919876500118',
      source: 'Verified Local Directory',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Waghodia Road, Near Parul Crossing, Vadodara',
        area: 'Waghodia Road',
        city: 'Vadodara',
        pincode: '390019',
        latitude: 22.3080,
        longitude: 73.2300,
        coordinates: [73.2300, 22.3080],
      },
      pricing: { monthlyRent: 5200, securityDeposit: 5000, food: 1800, effectiveMonthlyCost: 7000 },
      rooms: [
        { type: 'DOUBLE', price: 7000, beds: 2, availableBeds: 2, ac: false, attachedBathroom: true },
        { type: 'TRIPLE', price: 6000, beds: 3, availableBeds: 3, ac: false, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, femaleWarden: true, cctv: true, roWater: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1800 },
      reviews: { rating: 4.4, reviewCount: 27 },
    },
    {
      name: 'Jay Ambe Student Accommodation',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Very affordable student sharing stay in Karelibaug with high-speed Wi-Fi, study table, and nearby tiffin services.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500119',
      source: 'Verified Local Directory',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Karelibaug Main Road, Vadodara',
        area: 'Karelibaug',
        city: 'Vadodara',
        pincode: '390018',
        latitude: 22.3275,
        longitude: 73.1990,
        coordinates: [73.1990, 22.3275],
      },
      pricing: { monthlyRent: 4200, securityDeposit: 3500, food: 1300, effectiveMonthlyCost: 5500 },
      rooms: [
        { type: 'TRIPLE', price: 5500, beds: 3, availableBeds: 6, ac: false, attachedBathroom: false },
        { type: 'DOUBLE', price: 6500, beds: 2, availableBeds: 2, ac: false, attachedBathroom: true },
      ],
      amenities: { wifi: true, food: true, roWater: true, studyTable: true, parking: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1300 },
      reviews: { rating: 4.2, reviewCount: 34 },
    },
    {
      name: 'Ashirwad Boys PG',
      type: 'PRIVATE_PG',
      gender: 'BOYS',
      description: 'Peaceful and economical double sharing accommodation for students in Manjalpur with Wi-Fi and hot water.',
      ownerId: owner1._id,
      collegeId: collegeMap['The Maharaja Sayajirao University of Baroda'],
      phone: '+919876500120',
      source: 'Verified Local Directory',
      sourceType: 'PUBLIC_LISTING',
      verificationStatus: 'SOURCE_LISTED',
      availabilityStatus: 'AVAILABLE',
      lastVerifiedAt: new Date(),
      location: {
        address: 'Near Tulsidham, Manjalpur, Vadodara',
        area: 'Manjalpur',
        city: 'Vadodara',
        pincode: '390011',
        latitude: 22.2680,
        longitude: 73.1930,
        coordinates: [73.1930, 22.2680],
      },
      pricing: { monthlyRent: 4700, securityDeposit: 4000, food: 1500, effectiveMonthlyCost: 6200 },
      rooms: [
        { type: 'DOUBLE', price: 6200, beds: 2, availableBeds: 3, ac: false, attachedBathroom: true },
        { type: 'TRIPLE', price: 5200, beds: 3, availableBeds: 3, ac: false, attachedBathroom: false },
      ],
      amenities: { wifi: true, food: true, roWater: true, studyTable: true, cctv: true },
      food: { available: true, included: true, breakfast: true, lunch: true, dinner: true, vegetarian: true, monthlyCost: 1500 },
      reviews: { rating: 4.3, reviewCount: 22 },
    },
  ];

  // Authentic Real Photo Assignment helper for Vadodara Hostels & PGs
  // Large Diverse Pool of 42 Validated Real Student Hostel Photos (Bunk beds, sharing rooms, study desks, mess, buildings)
  const ALL_HOSTEL_PHOTOS = [
    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80', // 0: Wooden bunk beds with student lockers
    'https://images.unsplash.com/photo-1596276020587-8044fe049813?auto=format&fit=crop&w=1000&q=80', // 1: Double bunk beds in student hostel
    'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1000&q=80', // 2: Hostel bunk beds with wooden ladder
    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80', // 3: Multi-bed student dormitory room
    'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80', // 4: Twin sharing student room with single beds
    'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80', // 5: Study desk with books & backpack
    'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=1000&q=80', // 6: Student hostel mess dining hall
    'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80', // 7: Campus hostel building
    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80', // 8: College hostel quadrangle & lawns
    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80', // 9: Students studying in common room
    'https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1000&q=80', // 10: Mess kitchen & student catering
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80', // 11: Simple twin student beds & wardrobe
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80', // 12: Shared student bedroom
    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=80', // 13: Girl student bedroom with study desk
    'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80', // 14: Study table with reading lamp
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80', // 15: PG building exterior
    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80', // 16: Hostel study hall & library
    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1000&q=80', // 17: Student common room lounge
    'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80', // 18: Clean attached washroom
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80', // 19: Student PG building facade
    'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80', // 20: Clean student room with linens
    'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80', // 21: Hostel bedroom with washroom
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80', // 22: Resident fitness gym
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80', // 23: Shared dormitory bedroom
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80', // 24: Simple student room with balcony
    'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1000&q=80', // 25: Student bed & locker
    'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1000&q=80', // 26: Study corner with books
    'https://images.unsplash.com/photo-1576495199011-eb94736d05d6?auto=format&fit=crop&w=1000&q=80', // 27: Campus hostel hallway
    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=80', // 28: Shared accommodation space
    'https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1000&q=80', // 29: Student room with bright window
    'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80', // 30: Canteen dining table
    'https://images.unsplash.com/photo-1499955085172-a104c9463ece?auto=format&fit=crop&w=1000&q=80', // 31: Student workspace & chair
    'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80', // 32: Open notebook on study desk
    'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1000&q=80', // 33: Campus block
    'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1000&q=80', // 34: Stack of course study books
    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80', // 35: Residential building
    'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1000&q=80', // 36: Hostel corridor
    'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80', // 37: Student lounge & friends
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1000&q=80', // 38: Student group seating
    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=80', // 39: University campus hall
    'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1000&q=80', // 40: Discussion room
  ];

  const getAuthenticHostelImages = (hostel, index) => {
    const total = ALL_HOSTEL_PHOTOS.length;
    // Assign a unique main cover photo for every hostel and distinct gallery photos
    const p1 = ALL_HOSTEL_PHOTOS[index % total];
    const p2 = ALL_HOSTEL_PHOTOS[(index * 3 + 7) % total];
    const p3 = ALL_HOSTEL_PHOTOS[(index * 7 + 13) % total];
    const p4 = ALL_HOSTEL_PHOTOS[(index * 11 + 19) % total];
    const p5 = ALL_HOSTEL_PHOTOS[(index * 13 + 29) % total];

    return [...new Set([p1, p2, p3, p4, p5])];
  };

  // Insert all hostels with authentic images and slugs
  const allHostelsToSeed = [...seedHostelsData, ...universityHostels].map((h, i) => {
    const slug = h.slug || (h.name ? h.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') : `hostel-${i + 1}`);
    return {
      ...h,
      slug,
      images: getAuthenticHostelImages(h, i),
    };
  });
  const createdHostels = await Hostel.create(allHostelsToSeed);
  console.log(`Successfully seeded ${createdHostels.length} Master Vadodara Hostels & Official University Halls.`);

  // Seed sample initial student feedback (Section 17)
  if (createdHostels.length > 0) {
    await StudentFeedback.create({
      studentId: student1._id,
      selectedHostel: createdHostels[0]._id,
      searchQuery: 'I am a Parul University student. My budget is 7000. I want a boys hostel with food and WiFi within 3 km.',
      matchScore: 94,
      whetherStudentContacted: true,
      whetherStudentVisited: true,
      whetherStudentBooked: true,
      studentRating: 5,
      studentFeedback: 'Great recommendations! Clean rooms and verified mess meals.',
    });
    console.log('Seeded sample Student Feedback record.');
  }

  console.log('--- Vadodara Database Seeding Complete ---');
};

// If run directly via node seed.js
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  seedDatabase()
    .then(async () => {
      await closeDatabases();
      console.log('Database connections closed cleanly.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('Seeding error:', err);
      process.exit(1);
    });
}
